-- MySQL Script generated by MySQL Workbench
-- Thu Sep 30 17:43:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Telefone` ;

CREATE TABLE IF NOT EXISTS `Telefone` (
  `tipo_telefone` INT NOT NULL,
  `numero_telefone` CHAR NOT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`tipo_telefone`, `numero_telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultas` ;

CREATE TABLE IF NOT EXISTS `consultas` (
  `id_consultas` INT NOT NULL,
  `horario` CHAR(11) NULL,
  `id_medico` CHAR NOT NULL,
  `paciente_id_nome` CHAR NOT NULL,
  `paciente_cpf` DECIMAL NOT NULL,
  `paciente_rg` DECIMAL NOT NULL,
  PRIMARY KEY (`id_consultas`, `id_medico`, `paciente_id_nome`, `paciente_cpf`, `paciente_rg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paciente` ;

CREATE TABLE IF NOT EXISTS `paciente` (
  `id_nome` CHAR NOT NULL,
  `cpf` DECIMAL NOT NULL,
  `rg` DECIMAL NOT NULL,
  `bairro` TEXT NULL,
  `cidade` TEXT(15) NULL,
  `Telefone_tipo_telefone` INT NOT NULL,
  `Telefone_numero_telefone` CHAR NOT NULL,
  `consultas_id_consultas` INT NOT NULL,
  `consultas_id_medico` CHAR NOT NULL,
  `consultas_paciente_id_nome` CHAR NOT NULL,
  `consultas_paciente_cpf` DECIMAL NOT NULL,
  `consultas_paciente_rg` DECIMAL NOT NULL,
  PRIMARY KEY (`id_nome`, `cpf`, `rg`, `Telefone_tipo_telefone`, `Telefone_numero_telefone`, `consultas_id_consultas`, `consultas_id_medico`, `consultas_paciente_id_nome`, `consultas_paciente_cpf`, `consultas_paciente_rg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `endereço` ;

CREATE TABLE IF NOT EXISTS `endereço` (
  `cep` CHAR NOT NULL,
  `numero_endereço` CHAR NULL,
  `rual` CHAR NULL,
  `paciente_id_nome` CHAR NOT NULL,
  `paciente_cpf` DECIMAL NOT NULL,
  `paciente_rg` DECIMAL NOT NULL,
  PRIMARY KEY (`cep`, `paciente_id_nome`, `paciente_cpf`, `paciente_rg`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hospital` ;

CREATE TABLE IF NOT EXISTS `Hospital` (
  `idHospital` INT NOT NULL,
  `consultas` INT NULL,
  `paciente` CHAR NOT NULL,
  `horario` CHAR NULL,
  `paciente_id_nome` CHAR NOT NULL,
  `paciente_cpf` DECIMAL NOT NULL,
  `paciente_rg` DECIMAL NOT NULL,
  `Telefone_tipo_telefone` INT NOT NULL,
  `Telefone_numero_telefone` CHAR NOT NULL,
  `endereço_cep` CHAR NOT NULL,
  PRIMARY KEY (`idHospital`, `paciente`, `paciente_id_nome`, `paciente_cpf`, `paciente_rg`, `Telefone_tipo_telefone`, `Telefone_numero_telefone`, `endereço_cep`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
